const sampleData = {
  products: [
    {
      id: 1,
      name: 'Bitcoin Tee',
      slug: 'bitcoin-tee',
      category: 'Bitcoin',
      image: '/images/p1.jpg',
      price: 39.99,
      countInStock: 10,
      coin: 'Bitcoin',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Bitcoin Shirt',
    },
    {
      id: 2,
      name: 'Litecoin Tee',
      slug: 'litecoin-tee',
      category: 'Litecoin',
      image: '/images/p2.jpg',
      price: 39.99,
      countInStock: 10,
      coin: 'Litecoin',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Litecoin Shirt',
    },
    {
      id: 3,
      name: 'Ripple Tee',
      slug: 'ripple-tee',
      category: 'Ripple',
      image: '/images/p3.jpg',
      price: 39.99,
      countInStock: 10,
      coin: 'Ripple',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Ripple Shirt',
    },
    {
      id: 4,
      name: 'Solana Tee',
      slug: 'solana-tee',
      category: 'Solana',
      image: '/images/p4.jpg',
      price: 39.99,
      countInStock: 10,
      coin: 'Solana',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Solana Shirt',
    },
  ],
};

export default sampleData;
