import bcrypt from 'bcryptjs';

const sampleData = {
  products: [
    {
      name: 'Bitcoin Tee',
      slug: 'bitcoin-tee',
      category: 'Bitcoin',
      creator: 'Alex Motor',
      image: '/images/p1.jpg',
      price: 39.99,
      countInStock: 10,
      collection: 'Bitcoin',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Bitcoin Shirt',
    },
    {
      name: 'Litecoin Tee',
      slug: 'litecoin-tee',
      category: 'Litecoin',
      creator: 'Alex Motor',
      image: '/images/p2.jpg',
      price: 39.99,
      countInStock: 10,
      collection: 'Litecoin',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Litecoin Shirt',
    },
    {
      name: 'Ripple Tee',
      slug: 'ripple-tee',
      category: 'Ripple',
      creator: 'Alex Motor',
      image: '/images/p3.jpg',
      price: 39.99,
      countInStock: 0,
      collection: 'Ripple',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Ripple Shirt',
    },
    {
      name: 'Solana Tee',
      slug: 'solana-tee',
      category: 'Solana',
      creator: 'Alex Motor',
      image: '/images/p4.jpg',
      price: 39.99,
      countInStock: 10,
      collection: 'Solana',
      rating: 4.25,
      numReviews: 0,
      reviews: [],
      description: 'High Quality Solana Shirt',
    },
  ],
  users: [
    {
      firstName: 'Alex',
      lastName: 'Motor',
      addresses: [
        {
          street: '123 Main St',
          street2: 'Apt 2b',
          city: 'Las Vegas',
          state: 'NV',
          zip: '89122',
          preferredShipping: true,
          preferredBilling: false,
        },
      ],
      email: 'boldwebdevelopment@gmail.com',
      password: bcrypt.hashSync('password'),
      userType: 'Admin',
    },
    {
      firstName: 'Alexandra',
      lastName: 'Deddario',
      addresses: [
        {
          street: '321 Main St',
          street2: '',
          city: 'Hollywood',
          state: 'CA',
          zip: '10189',
          preferredShipping: false,
          preferredBilling: true,
        },
      ],
      email: 'adeddario@gmail.com',
      password: bcrypt.hashSync('password'),
      userType: 'Customer',
    },
  ],
};

export default sampleData;
